# Generated by Django 4.1.5 on 2023-01-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
