# Generated by Django 4.1.5 on 2023-01-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_chat', '0002_rename_owner_message_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
