# Generated by Django 4.1.5 on 2023-01-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_chat', '0004_chat_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
