# Generated by Django 4.1.5 on 2023-01-15 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posts_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posting_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 11, 53, 47, 270547, tzinfo=datetime.timezone.utc)),
        ),
    ]
