# Generated by Django 4.1.5 on 2023-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posts_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='posting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
