# Generated by Django 4.1.5 on 2023-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_posts_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile avatar'),
        ),
    ]
